apiVersion: apps/v1
kind: Deployment
metadata:
  name: permitting-pipeline-test
  namespace: a1b9b0-dev
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 0
  template:
    metadata:
      labels:
        DataClass: High
        app: httpd
        deployment: permitting-pipeline-test
    spec:
      containers:
        - name: permitting-pipeline-test
          image: >-
            image-registry.openshift-image-registry.svc:5000/a1b9b0-dev/permitting-pipeline-test@sha256:139156be349676036c1cba04898260592a11a947391d3bbc10e1a4f001339e04
          envFrom:
            - configMapRef:
                name: ats-pipeline
            - secretRef:
                name: ats-database
            - secretRef:
                name: ods-database
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

