apiVersion: batch/v1
kind: Job
metadata:
  name: permitting-pipeline-job
  namespace: a1b9b0-dev
spec:
  replicas: 0
  template:
    metadata:
      labels:
        DataClass: High
    spec:
      containers:
        - name: permitting-pipeline-test
          image: >-
            image-registry.openshift-image-registry.svc:5000/a1b9b0-dev/permitting-pipeline-test@sha256:139156be349676036c1cba04898260592a11a947391d3bbc10e1a4f001339e04
          envFrom:
            - configMapRef:
                name: fta-pipeline
            - secretRef:
                name: fta-database
            - secretRef:
                name: ods-database
          resources: 
            requests:
              memory: '1G'
              cpu: '1'
            limits:
              cpu: '2'
              memory: '2G'
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

